version: '3.8'

services:
  frontend:
    build: ./frontend
    # HAPUS ports:80 - akan dihandle oleh NPM
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=/api
    networks:
      - lpi-npm-network  # Network yang sama dengan NPM
    container_name: lpi_abata_frontend

  backend:
    build: ./backend
    ports:
      - "5001:5001"  # Biarkan untuk development access
    environment:
      - DB_HOST=database
      - DB_USER=lpi_user
      - DB_PASSWORD=AbataSecure123!
      - DB_NAME=menu_app
      - DB_PORT=5432
      - PORT=5001
    depends_on:
      - database
    networks:
      - lpi-npm-network  # Network yang sama
    container_name: lpi_abata_backend

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=menu_app
      - POSTGRES_USER=lpi_user
      - POSTGRES_PASSWORD=AbataSecure123!
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lpi-npm-network  # Network yang sama
    container_name: lpi_abata_database

volumes:
  postgres_data:

networks:
  lpi-npm-network:
    external: true  # Gunakan network external
